version: "3"

services:
  poll:
    build: ./poll
    ports:
       - 5000:80
    depends_on:
      - redis
    networks:
      - poll-tier
    restart: always
    environment:
      REDIS: redis

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - poll-tier
      - back-tier
    restart: always
    environement:
      PORT: 6379

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier
    restart: always
    environment:
      REDIS: "redis"
      DB: "db"

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier
      - result-tier
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  result:
    build: ./result
    ports:
      - 5001:80
    restart: always
    depends_on:
      - db
    networks:
    - result-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
