version: "3"

services:
  poll:
    build: ./poll
    ports:
       - 5000:80
    depends_on:
      - redis
    networks:
      - poll-tier
    restart: always
    environment:
      REDIS_HOST: "redis"
      OPTION_A: "Ansible"
      OPTION_B: "Chef"
      OPTION_C: "Puppet"
      OPTION_D: "SaltStack"

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
    restart: always
    environment:
      PORT: 6379

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier
      - result-tier
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier
    restart: always
    environment:
      REDIS_HOST: "redis"
      OPTION_A: "Ansible"
      OPTION_B: "Chef"
      OPTION_C: "Puppet"
      OPTION_D: "SaltStack"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  result:
    build: ./result
    ports:
      - 5001:80
    restart: always
    depends_on:
      - db
    networks:
    - result-tier
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
